### ISSUE TITLE
Patroneos does not pass through Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by michaeljyeates** [EOSIO/patroneos#28] opened 2018-06-05 15:02 UTC
The following line is put into the nodeos configuration but Access-Control-Allow-Origin is not sent in the response headers from patroneos

`access-control-allow-headers = *`

**Comment by chris-allnutt** [comment] 2018-06-05 15:22
Can you please send a request directly to the node without patroneous and verify that the Access Control header is there in the non proxied response?

**Comment by ericiles** [comment] 2018-06-05 15:41
@michaeljyeates, I have been unable to reproduce this. I just configured nodeos to send the Access-Control-Allow-Origin headers, and then did a request through patroneos, which forwarded the header as expected.

```
Access-Control-Allow-Origin: *
Content-Type: application/json
Server: WebSocket++/0.7.0
Date: Tue, 05 Jun 2018 15:36:53 GMT
Content-Length: 488
````

**Comment by redjade** [comment] 2018-06-05 16:12
Try `access-control-allow-origin` with asterisk in nodeos config. `access-control-allow-headers` is for specifying headers to allow, such as `Content-Type` and custom HTTP header.

**Comment by ericiles** [comment] 2018-06-05 17:36
It appears the issue is the wrong configuration parameter within the nodeos config.ini was set as pointed out by @redjade. I am going to go ahead and close this out. Feel free to comment if you have further issues.

**Closed by ericiles** 2018-06-05 17:36 UTC
